Title: First God's Sanctuary
Book: 1
Section: 1
CSS:../Styles/style.css
viewport: width=device-width
  
  ## Book One
#### of Super Gene 

<figure>
<img src="../Images/gem.gif" alt="gem" id="gem" width="120" height="60" />
</figure>

### Chapter 1 - Chapter 424
br>
<br>
<br>
<br>
  
> Written by Twelve Winged Burning Seraphim
>
> Compiled and edited by Max Ludden.
