Title: The Systems of Chaos and the Very High
Book: 8
viewport: width=device-width
CSS: ../Styles/style.css

## The Systems of Chaos and the Very High
### End of Book Eight
<figure>
	<img src="../Images/gem.gif" alt="gem" id="gem" width="240" height="120" />
</figure>

##### The Story Continues in Book Nine
#### Meeting God and Fighting Sacred...
