Title: The Systems of Chaos
Book: 8
Section: 12
Part: 1
CSS:../Styles/style.css
viewport: width=device-width
  
  ## Part One

<figure>
<img src="../Images/gem.gif" alt="gem" id="gem" width="120" height="60" />
</figure>
  
### Chapter 2444 - Chapter 2639
<br>
<br>
<br>
<br>
  
> Written by Twelve Winged Burning Seraphim
>
> Compiled and edited by Max Ludden.
