Title: Second God's Sanctuary
Book: 2
viewport: width=device-width
CSS: ../Styles/style.css

## Second God's Sanctuary
### End of Book Two
<figure>
	<img src="../Images/gem.gif" alt="gem" id="gem" width="240" height="120" />
</figure>

##### The Story Continues in Book Three
#### Third God's Sanctuary...
