Title: Second God's Sanctuary
Book: 2
Section: 2
CSS:../Styles/style.css
viewport: width=device-width
  
  ## Book Two
#### of Super Gene 

<figure>
<img src="../Images/gem.gif" alt="gem" id="gem" width="120" height="60" />
</figure>

### Chapter 425 - Chapter 882
br>
<br>
<br>
<br>
  
> Written by Twelve Winged Burning Seraphim
>
> Compiled and edited by Max Ludden.
