Title: Part Two\nFifth God's Sanctuary
Section: 5
Part: 2
CSS:../Styles/style.css
viewport: width=device-width

## Part Two

<figure>
<img src="../Images/gem.gif" alt="gem" id="gem" width="120" height="60" />

</figure>

### Chapter 1680 - Chapter 1711

<br><br><br><br>

#### Written by Twelve Winged Burning Seraphim
#### Compiled and edited by Max Ludden.
