Title: Meeting God and Fighting Sacred
Book: 9
viewport: width=device-width
CSS: ../Styles/style.css

## Meeting God and Fighting Sacred
### End of Book Nine
<figure>
	<img src="../Images/gem.gif" alt="gem" id="gem" width="240" height="120" />
</figure>

##### The Story Continues in Book Ten
#### The Universe of Kingdoms and Quin Kiu...
