Title: Blade and Eclipse
Book: 6
Section: 9
Part: 2
CSS:../Styles/style.css
viewport: width=device-width
  
  ## Part Two

<figure>
<img src="../Images/gem.gif" alt="gem" id="gem" width="120" height="60" />
</figure>
  
### Chapter 2166 - Chapter 2204
<
<br>
<br>
<br>
<br>
  
> Written by Twelve Winged Burning Seraphim
>
> Compiled and edited by Max Ludden.
