Title: The Very High
Section: 13
Part: 2
CSS:../Styles/style.css
viewport: width=device-width

## Part Two

<figure>
<img src="../Images/gem.gif" alt="gem" id="gem" width="120" height="60" />

</figure>

### Chapter 2640 - Chapter 2765

<br><br><br><br>

#### Written by Twelve Winged Burning Seraphim
#### Compiled and edited by Max Ludden.
