Title: Third God's Sanctuary
Section: 3
Part: 0
CSS:../Styles/style.css
viewport: width=device-width

## Book Three of Super Gene

<figure>
<img src="../Images/gem.gif" alt="gem" id="gem" width="120" height="60" />

</figure>

### Chapter 883 - Chapter 1338


#### Written by Twelve Winged Burning Seraphim
#### Compiled and edited by Max Ludden.
