Title: First God's Sanctuary
Book: 1
viewport: width=device-width
CSS: ../Styles/style.css

## First God's Sanctuary

### Book One

<figure>

<img src="../Images/gem.gif" alt="gem" id="gem" width="240" height="120" />

</figure>

Written by Twelve Winged Burning Seraphim
Complied and Edited by Max Ludden


